### ISSUE TITLE
♻️ "Refresh" component - change icon color and animation 

### ISSUE THREAD

**Issue by Madina-Mamysheva** [teletrace/teletrace#1300]
Cc: @tvaintrob @OfirD55 @Tavh 

Hi

## Pain

"Refresh" component requires some improvements as it looks quite subtle now (based on the collected feedback). To enhance the current state, please apply the following changes: 
 - Change icon color to Primary (#00cde7)
 - Increase the space between "Spans" title and refresh component (change margin-right to 20px)
 - Replace the animation displayed when the "Live mode" is active (like this https://app.lottiefiles.com/share/ffaff813-6596-4d22-9649-2fe466ea895d)

## Tasks

- [x] Change icon color to Primary (#00cde7)
- [x] Increase the space between "Spans" title and refresh component (change margin-right to 20px)
- [x] Replace the animation displayed when the "Live mode" is active (https://app.lottiefiles.com/share/ffaff813-6596-4d22-9649-2fe466ea895d)

## Screenshots

**Expected look:**

https://user-images.githubusercontent.com/119161511/214648594-ad6afbd5-8a3a-4076-ba60-64bdbb530ee6.mov

Regarding animation: please, let me know which format do you need (JSON, SVG, etc)
Thanks!
