### ISSUE TITLE
📚️ Trace View / New Layout + Overview Panels

### ISSUE THREAD

**Issue by itaykat** [teletrace/teletrace#1356]
## Problem

The existing page layout makes it hard for the user to navigate through the trace, which results in a high cognitive load.

## Audience

Trace View users.

## Proposed Work

A new layout that will better represent the node graph, timeline, details panel, and the interaction and synchronicity between them.

## Incentive

Enable more convenient and intuitive navigation within the trace.  

## Tasks

- [ ] Horizontal Trace graph layout
- [ ] Enhanced Node clicking behavior
- [ ] Enhanced Edge clicking behavior
- [ ] Trace Overview bar

**Comment by haimrait** [comment]
Decided not to continue with this issue
