### ISSUE TITLE
📚️ Span Search / RED metrics Charts

### ISSUE THREAD

**Issue by itaykat** [teletrace/teletrace#658]
# Problem

Individual spans and traces can help troubleshoot a production issue, but getting to the right “exemplar-trace” that represents the problem is hard with nothing but filters and trace view to jump between.

# Audience

All users troubleshoot issues using traces.

# Proposed Work

Three charts that represent RED metrics: requests, error, duration. 

1. **Requests chart** - representing all the request per second. 
2. **Errors chart** - representing all `http.status.code` and `non-http` errors broken down by status code or non-http. 
3. **Latency chart** - representing the latency of the requests.

# Incentive

Helping the users get immediate insights regarding the span dataset they’re working with, like spikes in errors over time, and changing behavior of traffic in their systems. Those insights can help them understand what to filter by, and get to the root cause faster.

## Intervals

- Interval will be automatically defined based on the max number of data points and the width of the users' screen/panel (Grafana example)

## Requests bar chart 

- Bars in the chart represent all the requests per second made within the selected timeframe. 

## Errors bar chart 

- Bars in the chart represent the number of errors, the bar is divided between the type of http and non-http code. 
- `http.status.code` errors are represented with a different color, each `http.status.code` will have the same color always in any situation. 

## Latency stacked line chart

- Should be a stacked line chart showing multiple percentiles
- Lines should be: p50 (Median), p90, p95, p99

# Walkthrough

# Interactions

**Default state**

- Charts will provide data based on the users chosen timeframe and applied filters.

**Hover**

- When hovering over one of the bars/line in either chart, user will see a time-synchronized tooltip across all three charts showing data based on the same specific time-range of the hover.
- When hovering over an error bar in the Errors chart, example`(404)`, that error will be highlighted in the tooltip.

**Click**

- User will be able to click on one specific bar in the Error chart
    - That will open a tooltip showing data only on the total errors of that `(404)` error bar and a **Views Spans** button
        - When users click on **View Spans**, it will trigger filters in all the table (span dataset, charts, custom timeframe, sidebar).
            - It has the same trigger as adding manually a custom filter and adding a filter of `http.status.code` `404`
                - It’s a shortcut for the user, better UX.
    - User will be able to **View Spans** also for Request or Latency chart by clicking somewhere in either of the charts.
        - Click on `p95` line in the Latency chart and **View spans** for that specific range.
    - Clicking on a value in the Legend (within the chart) will **only** filter the chart for that value
        - Example - clicking on `404` in the Legend of Error chart will only filter the chart by `404`requests.
            - This will not influence anything else in the table.

**************************Zoom-in/Highlighting************************** 

- User will be able to zoom-in/highlight with the mouse over any chart to filter a specific time range.

**Hiding graphs** 

- User will have a button to hide the graphs
    - The total number of Requests, Errors and Latency will still show up in text. 

**Live Mode is ON**

- When Live Mode is ON, charts should provide data based on the timeframe selected by the user (1H, 1D, 3D, 1W)
    - The time on the graph should expand while the Live Mode is on showing new results - until the user refreshes the page through the Refresh Button or browser.

## Mockups
**Design** https://www.figma.com/file/XHENquLcsodYHHKb923uM1/Telescope?node-id=8340%3A88668&t=NOj2Yd8cYsdeg3MN-4

**Prototype** (https://www.figma.com/proto/XHENquLcsodYHHKb923uM1/Telescope?page-id=8687%3A90061&node-id=10077%3A127901&viewport=636%2C-1145%2C0.35&scaling=min-zoom&starting-point-node-id=9999%3A119737)

https://user-images.githubusercontent.com/119161511/215979989-0b8adddf-f590-442a-a686-bc00145c2ce6.mov

- General view
![Charts - RED metrics](https://user-images.githubusercontent.com/119161511/216036494-cfe460f9-70dd-4fe1-ae82-dc126656d076.png)

- Synced tooltips
![Charts - RED metrics (synced tooltips)](https://user-images.githubusercontent.com/119161511/216036422-d279e8f0-bbfd-44f3-8297-ba6a8e533891.png)

- Hover over bar
![Charts - RED metrics (hover over Error)](https://user-images.githubusercontent.com/119161511/216294934-1a8a91b5-71e7-482a-a8fb-5c4c5e5c61c8.png)

- Select spans 
![Charts - RED metrics (select error type)](https://user-images.githubusercontent.com/119161511/216036319-8d68cff4-93c2-4790-80f7-5058227a2e04.png)

- Zoom in / select specific time frame
![Charts - RED metrics (zoom)](https://user-images.githubusercontent.com/119161511/216036244-97f6759c-b01a-4faa-99de-02c80c550a6e.png)

 - Filter by span_status code: OK
![Charts - RED metrics (OK)](https://user-images.githubusercontent.com/119161511/216036161-db2d71f8-4d63-48aa-9030-f14af0bb87ed.png)

 - Filter by span_status code: ERROR
![Charts - RED metrics (errors)](https://user-images.githubusercontent.com/119161511/216036182-6cc8d172-be5b-41da-8380-a7a3ee382c67.png)

# Future Enhancements Proposals
- Minimize/expand one or more charts from the list

## Tasks

- [x] #1592
- [x] #1600
- [ ] Implement OpenSearch API
- [ ] Implement Sqlite API
- [ ] Research Charting Library (recharts / chart.js / canvasjs) 
- [ ] #1630

**Comment by fmassot** [comment]
The mockups are very nice. IMHO, this is a key feature that is missing in the current OSS tools.

Jeager recently added the [Service Performance Monitoring (SPM)](https://www.jaegertracing.io/docs/1.44/spm/) but it uses dedicated metric storage and not the spans directly, so this requires more setup.

Do you plan to work on this feature?

**Comment by ophiryael** [comment]
Hi @fmassot, we've just started working on this feature. As a first step, we are working on supporting it in both Elasticsearch and OpenSearch.
Please let us know if you have any suggestions on improving the spec above.
