### ISSUE TITLE
♻️ Custom filters popover: width improvement for Key and Operator fields + add "X" icon for Value field ("contains/does not contain")

### ISSUE THREAD

**Issue by Madina-Mamysheva** [teletrace/teletrace#852]
Cc: @OfirD55 @tvaintrob @shaqued 

Hello

## Pain

The custom filter component needs some minor improvements. Please, apply the following fixes: 
 - Keep the Key dropdown width fixed (currently it changes depending on the content size).
 - Increase the operator field width so it will be equal to it's dropdown menu and align the dropdown to the left
 - Add "X" icon (appears on hover) to clear the input for the Value field for "contains/does not contain" operators

## Tasks

- [x] Key dropdown menu: increase the width and keep it fixed
- [x] Operator selection: increase the field width to keep it aligned to the dropdown list
- [x] Value field: add "X" icon when the input exist (related to "contains/does not contain" operators)

## Screenshots

**Key field dropdown menu**

- Current look: <img width="1792" alt="Screenshot 2022-12-21 at 15 00 04" src="https://user-images.githubusercontent.com/119161511/208921067-68ded220-86b3-41da-8229-4699e757de5f.png">

- Expected look: <img width="966" alt="Screenshot 2022-12-21 at 15 52 17" src="https://user-images.githubusercontent.com/119161511/208921521-fad624f3-034c-4bb7-8072-486de3fb362a.png">

----------------------------------------------------------------------------------------------------------------------------------

**Operator input field**

- Current look: <img width="966" alt="Screenshot 2022-12-21 at 15 54 38" src="https://user-images.githubusercontent.com/119161511/208921918-45eb4e19-bcec-4df7-8112-38d0dd2ec866.png">

- Expected look: <img width="966" alt="Screenshot 2022-12-21 at 15 55 03" src="https://user-images.githubusercontent.com/119161511/208922180-43e9ece6-d8ec-4fb6-b9e4-cad04ab120d0.png">

----------------------------------------------------------------------------------------------------------------------------------

**X icon for the "Value" input field**

- Current look: <img width="875" alt="Screenshot 2022-12-21 at 17 54 27" src="https://user-images.githubusercontent.com/119161511/208947608-a86a8d0e-e28a-4444-b180-12ef5f14d5f6.png">

- Expected look: <img width="832" alt="Screenshot 2022-12-21 at 17 53 09" src="https://user-images.githubusercontent.com/119161511/208947636-1fe18935-979e-433d-b65a-b95322fb8a28.png">

Thanks!
