### ISSUE TITLE
🐛 Sidebar filters - spacing and font improvement

### ISSUE THREAD

**Issue by Madina-Mamysheva** [teletrace/teletrace#853]
Cc: @tvaintrob @OfirD55 

Hi

## Describe the Bug

Go to https://app.lupaproject.io/ and view the sidebar with the filters. Currently it looks quite loose and the section titles are not bold enough. Please apply the following changes as:

- reduce the space between the checkboxes (32px)
- make category titles bold (font-weight 700 or "bold")
- apply cost-to-cost hover effect 
- reduce top-bottom padding for the checkboxes container below the title (top-padding: 0px, bottom-padding: 8px)

![Frame 212](https://user-images.githubusercontent.com/119161511/209083207-7c73d8ec-3c91-4bd2-9bf4-86fac32a8a2c.png)

## Tasks

- [ ] Reduce list items height to from 42px to 32px
- [ ] Make category titles more prominent (font-weight: 700/bold)
- [ ] Make cost-to-cost hover effect for the list items (checkboxes)
- [ ] Reduce the padding for the checkboxes container (top-padding: 0px, bottom-padding: 8px)

## Screenshots

![Frame 213](https://user-images.githubusercontent.com/119161511/209085065-1d945676-4426-4574-b907-cb844f232363.png)
