### ISSUE TITLE
👷 CI: Create gitHub action to run e2e tests

### ISSUE THREAD

**Issue by BaruchReut** [teletrace/teletrace#862]
## Pain
gitHub action for running e2e tests in the CI workflow is missing

## Suggested Solution
Create a gitHub action that will run the e2e tests after a PR was approved but before merging to master.

## Tasks
- [ ]  use gitHub matrix to run all tests per DB  - currently we support elastic
- [ ]  run docker compose without sending spans
- [ ]  run tests ( can be "echo true")
- [ ]  wait for all tests in matrix to finish, if one failed - fail the process
