### ISSUE TITLE
📚️  Support OpenSearch as Storage Plugin

### ISSUE THREAD

**Issue by haimrait** [teletrace/teletrace#969]
## Problem

Currently we support only ElasticSearch (either self hosted or managed by ElasticCloud) as a production grade traces storage solution, in order to support users who are using AWS as their main cloud provider with more storage options we should support OpenSearch in addition to existing storage solutions.

## Audience

- AWS users who are already manages their infrastructure in AWS
- Casual users who prefer to use managed storage solution and prefer OpenSearch

## Proposed Work

Support additional storage plugin for OpenSearch

## Incentive

This will enable users who already familiar or uses OpenSearch to more easily deploy and use Lupa

## Tasks
- [ ] Implement OpenSearch connector
- [ ] Implement spanreader plugin to support OpenSearch (query)
- [ ] Implement OpenSearch-based tags querying
- [ ] Create docker-compose file for OpenSearch-based deployment
- [ ] Create and Clean E2E Tests for OpenSearch
